# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ruina\PycharmProjects\autotix\nightly\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(389, 254)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progres_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progres_bar.setProperty("value", 24)
        self.progres_bar.setObjectName("progres_bar")
        self.gridLayout.addWidget(self.progres_bar, 3, 1, 1, 1)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\Ruina\\PycharmProjects\\autotix\\nightly\\../1x/logo_nightly_sm.png"))
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 0, 1, 2)
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setObjectName("run_button")
        self.gridLayout.addWidget(self.run_button, 3, 0, 1, 1)
        self.text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_browser.setObjectName("text_browser")
        self.gridLayout.addWidget(self.text_browser, 1, 0, 1, 2)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 389, 21))
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.menu_about = QtWidgets.QAction(main_window)
        self.menu_about.setObjectName("menu_about")
        self.menu_instructions = QtWidgets.QAction(main_window)
        self.menu_instructions.setObjectName("menu_instructions")
        self.menu_help.addAction(self.menu_instructions)
        self.menu_help.addAction(self.menu_about)
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

        self.run_button.clicked.connect(self.run_clicked)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "AutoTix - Nightly"))
        self.run_button.setText(_translate("main_window", "Run"))
        self.text_browser.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Make sure you have pulled a report and saved it to your </span><span style=\" font-size:9pt; font-weight:600;\">Downloads</span><span style=\" font-size:9pt;\"> folder.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Click </span><span style=\" font-size:9pt; font-weight:600;\">Run</span><span style=\" font-size:9pt;\"> to begin.</span></p></body></html>"))
        self.menu_help.setTitle(_translate("main_window", "Help"))
        self.menu_about.setText(_translate("main_window", "About"))
        self.menu_instructions.setText(_translate("main_window", "Instructions"))

    def run_clicked(self):
        print("Run button clicked!")


